package com.example.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.platform.LocalLayoutDirection
import androidx.compose.ui.unit.LayoutDirection

enum class AppLanguage(val code: String, val displayName: String, val layoutDirection: LayoutDirection) {
    ENGLISH("en", "English", LayoutDirection.Ltr),
    ARABIC("ar", "العربية", LayoutDirection.Rtl)
}

data class AppStrings(
    val appName: String,
    val searchPlaceholder: String,
    val allNotes: String,
    val starred: String,
    val lockedNotes: String,
    val archive: String,
    val trash: String,
    val folders: String,
    val createFolder: String,
    val folderName: String,
    val settings: String,
    val noNotesFound: String,
    val createFirstNote: String,
    val noteTitle: String,
    val noteContent: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val restore: String,
    val deletePermanently: String,
    val pinNote: String,
    val unpinNote: String,
    val lockNote: String,
    val unlockNote: String,
    val archiveNote: String,
    val unarchiveNote: String,
    val shareNote: String,
    val exportNote: String,
    val securityAndPrivacy: String,
    val enableAppLock: String,
    val changePassword: String,
    val setPassword: String,
    val enterPassword: String,
    val confirmPassword: String,
    val wrongPassword: String,
    val passwordSetSuccess: String,
    val passwordRemoved: String,
    val language: String,
    val selectLanguage: String,
    val english: String,
    val arabic: String,
    val theme: String,
    val lightTheme: String,
    val darkTheme: String,
    val systemTheme: String,
    val drawingPad: String,
    val clearDrawing: String,
    val addTag: String,
    val tags: String,
    val colorPalette: String,
    val clearTrash: String,
    val emptyTrashWarning: String,
    val noteLockedPrompt: String,
    val enterPasswordToAccessNote: String,
    val storageAndData: String,
    val totalNotes: String,
    val appInfo: String,
    val version: String,
    val securityHelpNote: String
)

val EnglishStrings = AppStrings(
    appName = "Notes",
    searchPlaceholder = "Search notes, tags, content...",
    allNotes = "All Notes",
    starred = "Starred",
    lockedNotes = "Protected Notes",
    archive = "Archive",
    trash = "Trash",
    folders = "Folders",
    createFolder = "New Folder",
    folderName = "Folder Name",
    settings = "Settings",
    noNotesFound = "No notes found",
    createFirstNote = "Tap + to create your first note",
    noteTitle = "Title",
    noteContent = "Start typing here...",
    save = "Save",
    cancel = "Cancel",
    delete = "Delete",
    restore = "Restore",
    deletePermanently = "Delete Permanently",
    pinNote = "Pin Note",
    unpinNote = "Unpin Note",
    lockNote = "Lock Note",
    unlockNote = "Unlock Note",
    archiveNote = "Archive",
    unarchiveNote = "Unarchive",
    shareNote = "Share",
    exportNote = "Export Text",
    securityAndPrivacy = "Security & Privacy",
    enableAppLock = "Password Lock",
    changePassword = "Change Password",
    setPassword = "Set App Password",
    enterPassword = "Enter Password / PIN",
    confirmPassword = "Confirm Password",
    wrongPassword = "Incorrect Password. Please try again.",
    passwordSetSuccess = "Password set successfully!",
    passwordRemoved = "Password lock removed",
    language = "Language",
    selectLanguage = "Select Language",
    english = "English",
    arabic = "العربية (Arabic)",
    theme = "Theme Mode",
    lightTheme = "Light",
    darkTheme = "Dark",
    systemTheme = "System Default",
    drawingPad = "Sketch & Draw",
    clearDrawing = "Clear Canvas",
    addTag = "Add Tag",
    tags = "Tags",
    colorPalette = "Note Background Color",
    clearTrash = "Empty Trash",
    emptyTrashWarning = "Are you sure you want to permanently delete all notes in Trash?",
    noteLockedPrompt = "Protected Note",
    enterPasswordToAccessNote = "Enter password to view this protected note",
    storageAndData = "Storage & Stats",
    totalNotes = "Total Active Notes",
    appInfo = "About Notes",
    version = "Version 1.0 (SQLite Encrypted)",
    securityHelpNote = "Passwords are encrypted and stored locally in SQLite database for maximum privacy."
)

val ArabicStrings = AppStrings(
    appName = "الملاحظات",
    searchPlaceholder = "البحث في الملاحظات والوسوم...",
    allNotes = "جميع الملاحظات",
    starred = "المفضلة",
    lockedNotes = "الملاحظات المحمية",
    archive = "الأرشيف",
    trash = "سلة المهملات",
    folders = "المجلدات",
    createFolder = "مجلد جديد",
    folderName = "اسم المجلد",
    settings = "الإعدادات",
    noNotesFound = "لا توجد ملاحظات",
    createFirstNote = "اضغط على + لإضافة أول ملاحظة",
    noteTitle = "العنوان",
    noteContent = "أكتب ملاحظتك هنا...",
    save = "حفظ",
    cancel = "إلغاء",
    delete = "حذف",
    restore = "استعادة",
    deletePermanently = "حذف نهائي",
    pinNote = "تثبيت الملاحظة",
    unpinNote = "إلغاء التثبيت",
    lockNote = "قفل الملاحظة",
    unlockNote = "إلغاء القفل",
    archiveNote = "أرشفة",
    unarchiveNote = "إلغاء الأرشفة",
    shareNote = "مشاركة",
    exportNote = "تصدير كنص",
    securityAndPrivacy = "الأمان والخصوصية",
    enableAppLock = "تفعيل قفل كلمة السر",
    changePassword = "تغيير كلمة السر",
    setPassword = "تعيين كلمة السر",
    enterPassword = "أدخل كلمة السر / PIN",
    confirmPassword = "تأكيد كلمة السر",
    wrongPassword = "كلمة السر غير صحيحة. حاول مرة أخرى.",
    passwordSetSuccess = "تم تعيين كلمة السر بنجاح!",
    passwordRemoved = "تم إلغاء قفل كلمة السر",
    language = "اللغة",
    selectLanguage = "اختر اللغة",
    english = "English (الإنجليزية)",
    arabic = "العربية",
    theme = "المظهر",
    lightTheme = "فاتح",
    darkTheme = "داكن",
    systemTheme = "افتراضي النظام",
    drawingPad = "الرسم والسكيتش",
    clearDrawing = "مسح اللوحة",
    addTag = "إضافة وسام",
    tags = "الوسوم",
    colorPalette = "لون خلفية الملاحظة",
    clearTrash = "تفريغ سلة المهملات",
    emptyTrashWarning = "هل أنت تأكد من حذف جميع الملاحظات في سلة المهملات نهائياً؟",
    noteLockedPrompt = "ملاحظة محمية بكلمة سر",
    enterPasswordToAccessNote = "أدخل كلمة السر لعرض هذه الملاحظة المحمية",
    storageAndData = "التخزين والإحصائيات",
    totalNotes = "إجمالي الملاحظات النشطة",
    appInfo = "حول التطبيق",
    version = "الإصدار 1.0 (تخزين محلي مشفر)",
    securityHelpNote = "كلمات السر محفوظة ومشفرة محلياً في قاعدة البيانات لتأمين خصوصيتك بالكامل."
)

val LocalAppStrings = staticCompositionLocalOf { EnglishStrings }
val LocalAppLanguageCode = staticCompositionLocalOf { "en" }

@Composable
fun ProvideAppLanguage(
    languageCode: String,
    content: @Composable () -> Unit
) {
    val language = if (languageCode == "ar") AppLanguage.ARABIC else AppLanguage.ENGLISH
    val strings = if (languageCode == "ar") ArabicStrings else EnglishStrings

    CompositionLocalProvider(
        LocalAppStrings provides strings,
        LocalAppLanguageCode provides languageCode,
        LocalLayoutDirection provides language.layoutDirection,
        content = content
    )
}
